#### 异常类对象

> 异常类对象的作用

* 可以将异常进行分类，即通过面向对象的方式并划分类别来编写异常类信息能够在之后的代码之中不去改变原有的try语句块，直接添加或者删除对应的某一类异常信息
* 能够保存信息和行为，即异常类对象能够提供一个给我们存储的上下文本信息并可以作为try处理器的一个工具实例来访问异常类的信息和相应的调用方法
* 支持类的继承，即可以在一个父异常类中定义一系列的异常信息输出格式，而通过子类异常来体现不同的信息和行为表现

##### 异常类对象适应python的后期版本
* 使用字符串异常,py2.x和py3.x都能够自定义异常类对象和字符串异常类对象

```python
# exception_object.py
def test_string():

    str_exce = u"this is the string exception"
    try:
        raise  str_exce
    except str_exce:
        print("caught the string exec")
```

* 基础的异常类对象
    * 字符串异常通过简单对象标识来进行匹配
    * 类对象异常通过父类继承的方式来进行匹配,即except抓住的异常类将以继承搜索树的方式进行匹配

* 类对象异常的优点
    * 能够以OOP的方式进行编程
    * 能够记住异常类信息的状态和行为信息
    
* 编写异常类
    * Exception superclass
    * Raising instances
    * Catching categories
    * Exception details
    
* 异常类的层次结构
     
##### python内置的异常类
* 内置异常类
    * BaseException
    * Exception
    * ArithmeticError
    * LookupError
    
* 内置的异常分类
    * By listing  ArithmeticError in a try
    * By listing ZeroDivisionError

* 默认异常类的显示和状态

* 自定义异常类的显示和状态

##### 自定义异常类数据和行为状态
* 提供类异常详细信息
* 提供异常类方法
    
    
#### 异常类的设计

##### 嵌套的异常处理机制
* 流程控制嵌套，通过对外提供函数式来封装然后嵌套在try的语句块中
* 语法嵌套，直接在try语句块中嵌套try的语句块

##### 异常使用场景
* 跳出多嵌套循环语句，类似于go to语句
* Exception并非都是Errors
* 函数能够在条件信号中使用raise语句来中断函数
* 处理文件和网络server的连接资源的建立，超时以及回收
* 使用外部的try语句块进行调试
* 执行正在运行处理的测试
* sys.exc_info核心信息
    * type is the exception class of the exception being handled.
    * value is the exception class instance that was raised.
    * traceback is a traceback object that represents the call stack at the point where the
exception originally occurred, and used by the  traceback module to generate error
messages
* 显示错误信息和trackbacks

##### 异常处理类的设计技巧与存在的陷阱
* 什么时候应该使用包装的异常类信息
    * Operations that commonly fail should generally be wrapped in  try statements
    * there are exceptions to the prior rule
    * You should implement termination actions in  try / finally statements to guarantee
their execution, unless a context manager is available as a  with / as option
    * It is sometimes more convenient to wrap the call to a large function in a single
try statement, rather than littering the function itself with many  try statements

* catching太多，应当避免使用空的except和Exception

* catching太少，可以使用基于class的异常分类
